# Utiliser une image de base Node.js
FROM node:20-alpine

# Créer un répertoire de travail
WORKDIR /usr/src/app

# Copier package.json et package-lock.json
COPY package.json ./

# Installer les dépendances
# ARG NODE_ENV
# RUN if [ "$NODE_ENV" = "production" ]; then \
#     npm ci --only=production; \
#     else \
#     npm install; \
#     fi
RUN npm i

# Copier le reste de l'application
COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev"]
