# Utiliser une image de base Node.js
FROM node:20-alpine

# Créer un répertoire de travail
WORKDIR /usr/src/app

# Copier package.json et package-lock.json
COPY package.json ./

# Installer les dépendances
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "production" ]; then \
    npm ci --only=production; \
    else \
    npm install; \
    fi

# Copier le reste de l'application
COPY . .

COPY wait-for-database.sh /usr/wait-for-database.sh
RUN chmod +x /usr/wait-for-database.sh

# Lire la méthode de démarrage et le port à partir de .env
# CMD ["sh", "-c", "npm run dev"]
CMD ["/usr/wait-for-database.sh", "db:3306", "--", "npm run dev"]
